### ISSUE TITLE
Unable to find an inherited method for function ‘dbListFields’ for signature ‘"MySQLConnection"’

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RMariaDB#46]
<a href="https://github.com/martinschmelzer"><img src="https://avatars0.githubusercontent.com/u/7760212?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [martinschmelzer](https://github.com/martinschmelzer)**
_Wednesday May 03, 2017 at 18:42 GMT_
_Originally opened as https://github.com/rstats-db/RMySQL/issues/199_

----

Got a homebrewed isntall of XAMPP. Connected to the db with 

```
con <- dbConnect(RMySQL::MySQL(), host = 'localhost', 
                 user ='user', password = 'pw', 
                 unix.socke='/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock',
                 dbname = 'dbname')
```

`dbListTables(con)` works fine and returns the single table that is inside the db. But when I then try

`dbListTables(con, 'tablename')` I get:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbListFields’ for signature ‘"MySQLConnection"’

Additional info:
Mac OS Sierra, R 3.4, DBI 0.6-1, RMySQL 0.11-5 

<MySQLConnection>
  Host:    localhost
  Server:  10.1.21-MariaDB
  Client:  5.5.1

**Comment by krlmlr** [comment]
@martinschmelzer: Duplicate of #29.

**Comment by msberends** [comment]
Still got this problem.

```r
> packageDescription("RMariaDB")
# Package: RMariaDB
# Version: 1.0-4
# Title: Database Interface and 'MariaDB' Driver
```

Looks like the `DBI` package does not support the S4 class `MariaDBConnection` yet. I'm turning back to the `RMySQL` package. Please fix!

**Comment by krlmlr** [comment]
@msberends: Adding identical comments to duplicate issues is not helpful. Deleting your comment and this message.
