### ISSUE TITLE
dbWriteTable doesn't respect transactions

### ISSUE THREAD

**Issue by carlganz** [rstats-db/RMariaDB#49]
Hello,

It appears transactions are used in the code for `RMariaDB::dbWriteTable`, which prevents users from rollingback insert queries. Perhaps there is a good reason for this, but it is not the case with `RMySQL`.

MRE:

```{R}
library(DBI)

conMySQL <- dbConnect(RMySQL::MySQL(),
                       host = host,
                       port = as.integer(port),
                       user = user,
                       password = password,
                       db = db)

conMariaDB <- dbConnect(RMariaDB::MariaDB(),
                      host = host,
                      port = as.integer(port),
                      user = user,
                      password = password,
                      db = db)

# add fake data
dbWriteTable(conMySQL, "test1", data.frame(a = 1, b = 2), row.names = FALSE, overwrite = TRUE)
dbWriteTable(conMariaDB, "test2", data.frame(a = 1, b = 2), row.names = FALSE, overwrite = TRUE)

# insert data inside transaction
dbBegin(conMySQL)
dbBegin(conMariaDB)

# calling dbbegin twice should error but doesn't
dbBegin(conMySQL)
dbBegin(conMariaDB)

dbWriteTable(conMySQL, "test1", data.frame(a = 3, b = 4), row.names = FALSE, append = TRUE)
dbWriteTable(conMariaDB, "test2", data.frame(a = 3, b = 4), row.names = FALSE, append = TRUE)

dbGetQuery(conMySQL, "select * from test1")
dbGetQuery(conMariaDB, "select * from test2")

dbRollback(conMySQL)
dbRollback(conMariaDB)

dbGetQuery(conMySQL, "select * from test1")
# rollback unsuccesful
dbGetQuery(conMariaDB, "select * from test2")
```

Thank you for all your hard work with this wonderful package.

**Comment by krlmlr** [comment]
Thanks. The `dbWriteTable()` implementation uses transactions internally, but neither MySQL nor MariaDB support nested transactions -- a `BEGIN` inside a transaction starts a new transaction instead. We need to fix `dbBegin()`, but then `dbWriteTable()` will raise an error in this example. Would that be a problem?

**Comment by carlganz** [comment]
So there is no way to insert data within a transaction?

Image someone buys something, you would want to create a row in a transactions table, and update the inventory table to remove the purchased item. It would be nice if you could rollback both the new row in the transaction table, and the update query to the inventory table if the inventory quantity is negative:

```{R}
dbBegin(con)
remove <- 5
dbWrite(con, "transaction", new_row)
dbExecute(con, "update inventory set quantity = quantity - ?", remove)
if (dbReadTable(con, "inventory")$quantity >= 0) {
  dbCommit(con)
} else {
  dbRollback(con)
}
```

**Comment by krlmlr** [comment]
My plan is:

1. Turn off autocommit mode when connecting.
2. Manually commit after each `dbClearResult()`, unless a manual transaction started with `dbBegin()` is active.
3. Manually commit with `dbCommit()`.
4. Manually rollback with `dbRollback()`.

This is consistent with the DBI specification. It is unfortunate that MySQL can't isolate DDL statements, so `dbWriteTable(create = TRUE)` will behave strangely when used with manual transactions, but I don't see a better way here. Happy to receive your feedback.

**Comment by carlganz** [comment]
Right, but it should be possible to use `dbWriteTable(append = TRUE)` in a transaction (sorry for not using `append=TRUE` earlier)

I suggest moving the transaction in `dbWriteTable` into `sqlCreateTable` or not explicitly calling the transaction when `append=TRUE`.
