### ISSUE TITLE
Distribute the RMariaDB Package through the "MariaDB Fundation" webpage (Not only CRAN)

### ISSUE THREAD

**Issue by jtelleriar** [rstats-db/RMariaDB#50]
First of all, thank you for making possible the RMariaDB package, it was a long-awaited package.

As regards this issue, I would recommend distributing "RMariaDB" package not only from CRAN; but also from the "MariaDB Foundation" webpage:
https://downloads.mariadb.org/

This will enable a better maintainance of the package, and a major visibility of it (and therefore, more support).

Maybe an issue could be opened in MariaDB's JIRA:
https://jira.mariadb.org/projects/MDEV/issues/MDEV-13514?filter=allopenissues

**Comment by krlmlr** [comment]
Thanks for raising this. We should look into this when the package hits CRAN, maybe we can start with a simple link?

**Comment by jtelleriar** [comment]
Yes, maybe we could ask for a link to RMariaDB in the R Foundation when it is on CRAN, or even ask for support from MariaDB Corporation or Foundation, which they will be probably be keen on giving.

The MariaDB development mailing list is the next one:
maria-developers@lists.launchpad.net

Thank you for your excellent work.
Juan

**Comment by carlganz** [comment]
It appears there is already some mention of this package: https://mariadb.com/kb/en/library/r-statistical-programming-using-mariadb-as-the-background-database/

**Comment by jtelleriar** [comment]
Yes, I was indeed the one who wrote that article.

The point is to offer it directly through the MariaDB Foundation Download
page as a community developed connector.

The PHP MySQL connector was also created by the MySQL community I think,
and was distributed (or said how to get it through CRAN) through the main
connector download webpage.

Thank you,
Juan

**Comment by jtelleriar** [comment]
Done.

A specific section for the package has been added at the MariaDB Knowledge Base.

Thank you,
Juab

**Comment by jtelleriar** [comment]
Juan*

**Comment by krlmlr** [comment]
Thanks, Juan. You mentioned support by the MariaDB foundation: Indeed, there is a [problem](https://jira.mariadb.org/browse/CONC-281) that is now fixed for Connector/C 2.3.4. I believe that the fix is required for RMariaDB, but it seems unclear if this change will make it to the "stable" repos of Ubuntu, Fedora, etc.. Would it be possible to backport (or otherwise make available) the relevant changes for the most important Linux distros, so that we can actually use MariaDB's connector for RMariaDB?
