### ISSUE TITLE
Suggestion: Return a Tibble instead of a data.frame

### ISSUE THREAD

**Issue by jtelleriar** [rstats-db/RMariaDB#51]
Maybe it would be a good idea that RMariaDB returns by default a Tibble instead of a data.frame:

https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html

**Comment by krlmlr** [comment]
I love the idea, but this will hurt compatibility (because all other backends then also would have to return tibbles for consistency) and also pull in an additional dependency.
