### ISSUE TITLE
compatibility MariaDB and Connector/C

### ISSUE THREAD

**Issue by bowerth** [rstats-db/RMariaDB#53]
Hello -
could you indicate which versions of MariaDB and Connector/C are supported? Using MariaDB 10.2.8 and the development version of https://github.com/MariaDB/mariadb-connector-c, I am getting issues with the driver.cpp, namely that `MYSQL_SERVER_VERSION` has not been declared.
When using the most recent versions of mariadb in Fedora 26 repos (mariadb-devel 10.1.25 and mariadb-connector-c-devel 2.3.3), `devtools::install()` complains about a missing `mariadb_version.h`
Grateful for any advice!

**Comment by bowerth** [comment]
- with MariaDB 10.2.8 (Fedora 26), "mysql_version.h" is located at `/usr/include/mysql/server/mysql_version.h`
- `mariadb_config --cflag` returns `-I/usr/include/mysql -I/usr/include/mysql/mysql`
- copying `/usr/include/mysql/server/mysql_version.h` to one of the directories solves the issue

**Comment by krlmlr** [comment]
Thanks for reporting. Installation should work smoothly on all platforms. How can I replicate this in a Docker container?

**Comment by bowerth** [comment]
thanks for looking into this -
the following works but in actual use mode, I get an error when trying to retrieve a table 

```
SELECT * FROM test
```

a `COUNT` operations works, however

```
SELECT COUNT(*) FROM test
```

PS: I am new to Docker, please excuse bad style

```
FROM registry.fedoraproject.org/fedora:26

RUN touch /etc/yum.repos.d/MariaDB.repo
RUN echo -e "[mariadb]\nname = MariaDB\nbaseurl = http://yum.mariadb.org/10.2/fedora/26/x86_64\ngpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB\ngpgcheck=1" > /etc/yum.repos.d/MariaDB.repo

RUN dnf update -y
RUN dnf install -y MariaDB-devel

RUN dnf install -y R

# required by git2r
RUN dnf install -y openssl-devel

# required by httr
RUN dnf install -y libcurl-devel

RUN Rscript -e 'install.packages("httr", repos="http://cran.us.r-project.org")'

RUN Rscript -e 'install.packages("devtools", repos="http://cran.us.r-project.org")'

# see https://github.com/rstats-db/RMariaDB/issues/53
RUN cp /usr/include/mysql/server/mysql_version.h /usr/include/mysql/mysql

# see https://github.com/rstats-db/RMySQL/issues/197
RUN ln -s /usr/lib64/libmariadbclient.a /usr/lib64/libmariadb.a

RUN Rscript -e 'devtools::install_github("rstats-db/RMariaDB")'

RUN Rscript -e 'library(RMariaDB)'
```

**Comment by krlmlr** [comment]
Thanks, the Dockerfile is awesome. I think I can work around the issues with the header file (2c5462af7f, currently running tests on Travis) but not the library name mismatch. We need to trust `mariadb_config` on that. I think we either need a different yum package, or this issue must be resolved upstream. Until that, we need to document the workarounds, maybe in the README?

**Comment by bowerth** [comment]
As mentioned in my previous message, I did not succeed retrieving any values from tables but only row counts. For the moment, I would only mention that compatibility problems with Fedora 26 exist? By the way, Fedora 27 is currently scheduled to be released at the end of October 2017, see [Releases/27/Schedule](https://fedoraproject.org/wiki/Releases/27/Schedule).

**Comment by krlmlr** [comment]
Trying in Fedora 27 now, will also try retrieving data via `dbGetQuery()`.

There seems to be a workaround (adding two symlinks) that allows installing, but it's of course useless if the package doesn't retrieve data. What happens if you run `dbGetQuery(con, "SELECT 1 AS a UNION SELECT 2")`?

**Comment by bowerth** [comment]
It is possible to run `dbGetQuery(con, "SELECT 1 AS a UNION SELECT 2")`

Update: I had no issue running the following commands:

```R
dbWriteTable(con, "mtcars", mtcars)
dbReadTable(con, "mtcars")
# You can fetch all results:
res <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = 4")
dbFetch(res)
dbClearResult(res)
```
The issue however persists for a larger table that was not exported from R but imported in MariaDB using the command line. Also, the following commands fail on the test DB with the mtcars table exported  from R:

- `dbListTables(con)`
- `dbListFields(con)`

**Comment by krlmlr** [comment]
This is very helpful, because I'm seeing potentially related problems with `dbListTables()` on OS X too.

I just spent some time finding out how to connect from inside Docker to the MySQL database on my development machine, the magic words are:

```sh
docker run --net=host --rm -ti ... mysql -h 127.0.0.1 -u $USER
```

**Comment by krlmlr** [comment]
@jeroen: Do you recall any upstream bugs in Connector/C affecting the processing of string and blob columns via `mysql_stmt_fetch_column()`?

**Comment by krlmlr** [comment]
Specifically, if the client doesn't call `mysql_stmt_store_result()`, strings and blobs seem to be unavailable. If I remove the relevant calls in the upstream tests, they start to fail: https://github.com/krlmlr/mariadb-connector-c/commit/5db25b0e0448046adec7bdf8ee8cbf47228be5ac.

**Comment by krlmlr** [comment]
@bowerth: Can you please try `remotes::install_github("rstats-db/RMariaDB@f-ci")` ?

**Comment by krlmlr** [comment]
Filed a JIRA issue: https://jira.mariadb.org/browse/CONC-281

**Comment by krlmlr** [comment]
@bowerth: Everything except linking against the wrong library is fixed in the f-ci branch which I'm about to merge. I'd rather not tweak the return value of `mariadb_config`, happy to review a PR that documents this problem.
