### ISSUE TITLE
All DATETIME values returned are "1969-12-31 16:59:59"

### ISSUE THREAD

**Issue by Bandytwin** [rstats-db/RMariaDB#54]
Hello,
When running the query "select * from table limit 10" all of the datetime fields returned have the value "1969-12-31 16:59:59", and is the case even when I filter the data (i.e. date_field >= '2017-08-10'). The data returned in all of the other fields is correct. I am running OSX and have seen this problem with R-version 3.4.1 and 3.3.3 (though I have only been able to replicate it on other OSX machines with R 3.3.3). This issue is not present when I use RMySQL.

Thanks,
Andrew

**Comment by noahwilliamsson** [comment]
@Bandytwin, @nancylin10: FWIW, I've opened a pull request for a similar issue on https://github.com/rstats-db/RMariaDB/pull/52.

Feel free to see if it works for you.  You can try installing it with:

> devtools::install_github("noahwilliamsson/RMariaDB")

**Comment by nancylin10** [comment]
yay! that fixed my issue! do you have any idea when that PR will be merged to master?

Thanks!
Nancy

**Comment by Bandytwin** [comment]
@noahwilliamsson thanks for the help! That seems to have solved the problem on my end as well. I am going to still leave this issue open for the time being because it is unclear to me why I haven't consistently run across it (i.e. why the code from Master worked on a coworker's OSX machine, but I needed the PR for mine).

**Comment by noahwilliamsson** [comment]
Thanks for the feedback, happy to hear that it solved the issues you were seeing.  I don't know if or when the PR (#52) will be merged.  Perhaps @krlmlr can shed some light on that?

**Comment by krlmlr** [comment]
Thanks for your patience, the PR is in master now. For the record, you can always use

```r
remotes::install_github("rstats-db/RMariaDB#52")
```

to install a particular unmerged PR.
