### ISSUE TITLE
Legacy mode available?

### ISSUE THREAD

**Issue by andrewkho** [rstats-db/RMariaDB#64]
RMariaDB is meant to be a drop-in replacement for RMySQL, however it handles datatypes very differently. For example, BIGINTs are now imported as integer64 instead of numeric, and SQL Date columns are imported as Date instead of character. All of these are improvements, however as it is supposed to be "drop-in replacement", is there a "legacy" mode so that I can use this instead of RMySQL without rewriting all the scripts that depend on data read from it?

**Comment by krlmlr** [comment]
Thanks. Maybe "drop-in" raises the expectations too high. We plan to support different data types for returning numbers at the DBI level (https://github.com/rstats-db/DBItest/issues/133, last comment), but I don't think we should inherit quirks from the existing implementation. With the current setup, you can migrate at your own pace -- RMySQL should be around and supported for quite some time, it's just in maintenance mode without active development.

**Comment by andrewkho** [comment]
Thanks for the quick response! I actually went back to double check I had read "drop-in replacement" right. 

The issue I have is that on my server (centOS 7), RMySQL does not compile if I uninstall MySQL and install MariaDB. If it's still in maintenance mode then I'll make a bug report there.

**Comment by krlmlr** [comment]
You had it right but I removed it to avoid this kind of expectation ;-)
