### ISSUE TITLE
SHOW PLUGINS returns nothing

### ISSUE THREAD

**Issue by nbenn** [rstats-db/RMariaDB#67]
Using RMariaDB v1.0-2 with both MariaDB 10.1.25 and MySQL 5.7.17, I'm not able to successfully run the `SHOW PLUGINS` statement (I get empty `df`'s).

```r
> root <- DBI::dbConnect(RMariaDB::MariaDB(), username = "root", password = "***")
> DBI::dbGetQuery(root, "SHOW PLUGINS")
data frame with 0 columns and 0 rows
```
With RMySQL v0.10.13, however, this works fine
```r
> DBI::dbGetQuery(root, "SHOW PLUGINS")
                            Name   Status               Type Library License
1                         binlog   ACTIVE     STORAGE ENGINE    <NA>     GPL
2          mysql_native_password   ACTIVE     AUTHENTICATION    <NA>     GPL
3             mysql_old_password   ACTIVE     AUTHENTICATION    <NA>     GPL
...
```
Please let me know whether I can provide further information for helping to solve this issue.

**Comment by krlmlr** [comment]
Thanks, I can replicate the problem on my system. This looks like an omission in the prepared statement API, which is used only by this package (and not yet by RMySQL).

Other queries are also affected, e.g. `SHOW PROCESSLIST`. The reason appears to be that the result set information is available only after actually running the query, unlike regular `SELECT` queries. (Need to call `mysql_stmt_execute()` before `mysql_stmt_result_metadata()`.)

**Comment by nbenn** [comment]
Indeed, adding
```cpp
if (!has_result()) {
  // try again after mysql_stmt_execute, in case pSpec_ == NULL
  pSpec_ = mysql_stmt_result_metadata(pStatement_);
}
```
to `execute`, as in nbenn/RMariaDB@978e87d5c0937f3955d8fc644ae3fda2d4dc1063 yields the desired result in case of my `SHOW PLUGINS` query. I don't know if this is a sensible solution though, as

> If you call mysql_stmt_result_metadata() after each mysql_stmt_execute(), the correct metadata is returned.   However, this workaround is too inefficient to use always, because too many calls would have to be made (1 per execute instead of 1 per prepare) ... [source](https://bugs.mysql.com/bug.php?id=42488)

It might be worth it to add a test for such queries to catch this type of behaviour. Should I also open an issue at DBItest?

**Comment by krlmlr** [comment]
Thanks for digging into it. We now know when to expect a result set: only with `dbGetQuery()/dbSendQuery()`, not with `dbExecute()`. We could pass this information to the C++ code and use this to reduce the number of `mysql_stmt_result_metadata()` calls. Happy to review a PR.

**Comment by nbenn** [comment]
I added a flag as per your suggestion (nbenn/RMariaDB@f5ef482). If you're interested, I'll gladly submit a PR.

There is one thing I'm not quite happy with: my approach for determining whether I'm in the statement or the query setting is by greping the call stack in `dbSendQuery()`. This seems a bit hacky, but `dbExecute()`, `dbSendStatement()` and `dbGetQuery()` all live in DBI, so I saw no other way. Any suggestions?

Initially I was worried with my solution that, as `execute()` is called from `bind()` in a loop, this will generate many calls to `mysql_stmt_result_metadata()` due to my changes. This, however is not the case. A PS query like
```r
iris_res <- DBI::dbSendQuery(con, "SELECT * FROM iris WHERE `Petal.Width` = ?")
DBI::dbBind(iris_res, list(seq(from = 0, to = 4, by = 0.1)))
DBI::dbFetch(iris_res)
DBI::dbClearResult(iris_res)
```
does not call `mysql_stmt_result_metadata()` in `execute()`. So I guess this is good news.

**Comment by krlmlr** [comment]
Thanks. We could implement the `dbSendStatement()` method in RMariaDB (similarly to `dbSendQuery()`), this would give full control.

Note that you can start a PR from your current changes, it will update if you push/force-push to the branch.

**Comment by nbenn** [comment]
Thanks for the PR protip. It's my first time. I will look into copying the `dbSendStatement()` DBI generic into RMariaDB.

**Comment by nbenn** [comment]
I now added `dbSendStatement()`. Happy to look into any feedback you have for my changes. Some unit tests fail, both on my machine and on travis. I don't think that this is due to my changes. I guess I started with code that already failed some tests. Please let me know if you think this is not the case and I'll try to work it out.
