### ISSUE TITLE
bugs in a for loop

### ISSUE THREAD

**Issue by RaymondSHANG** [rstats-db/RMariaDB#71]
Hi,dear RMariaDB developers,
   I connected to MySQL database using RMariaDB and run the following code. After a second, it turned the following error message:
**Error in result_fetch(res@ptr, n) : Inactive result set**
   I looked in the running process, and it seemed to corrupt randomly. As I can get the value of 'i' after the program returned the error message, and it seems to be quite random. Actually, I could rerun the code by setting a new starting point of 'i', and the program would go and stop a while later.
  I guess maybe something is wrong with 
"  
 res <-dbSendQuery(con,sql_s)
  result <- dbFetch(res)
  homologID <-result$homologID[1]
  dbClearResult(res)
"
Sometimes, it runs 'dbClearResult(res)' before 'dbFetch(res)'.
Could anyone help?

My code:
for (i in 1: length(d3$geneSymbol)){
  rat_sy <- d3$geneSymbol[i]
  sql_s <- paste0("select * from rat where symbol = '",rat_sy,"'")
  res <-dbSendQuery(con,sql_s)
  result <- dbFetch(res)
  homologID <-result$homologID[1]
  dbClearResult(res)
  if(is.na(homologID)){
    noHomo[j]<-rat_sy
    j<-j+1
    d3$humangene[i] <- rat_sy
  }else{
    sql_s <- paste0("select * from human where homologID = ",homologID,"")
    #dbClearResult(res2)
    res2 <-dbSendQuery(con,sql_s)
    result2 <- dbFetch(res2)
    dbClearResult(res2)
    ##Three possible results:1.empty result2,2.unique hit 3.multiple hits
    if(length(result2$symbol)==0){
      noHomo[j]<-rat_sy
      j<-j+1
      d3$humangene[i] <- rat_sy
    }else if(length(result2$symbol)==1){
      #one hit! best match
      d3$humangene[i] <- result2$symbol[1]
    }else{
      tmp <- toupper(rat_sy)
      tmp2 <- result2$symbol
      if(tmp %in% tmp2){
        #exact match
        d3$humangene[i] <- tmp
      }else{
        #else use the first one to present
        d3$humangene[i] <- result2$symbol[1]
        moreHomo[k] <- rat_sy
        k<k+1
      }
    }
  }
}

**Comment by RaymondSHANG** [comment]
I fixed the problem by adding one additional connection:
con2 <- dbConnect(RMariaDB::MariaDB(), dbname = "genehomolog",user="***",password="***")

And use con2 for the second query:
res2 <-dbSendQuery(con2,sql_s)

Then the program goes smoothly to the end.

**Comment by krlmlr** [comment]
RMariaDB supports only one active results set per connection for now. We'll see if it's worthwhile to lift this restriction in the future.
